name: Mac Raw CI
on:
  pull_request:
    branches:
      - '*'
      - '!master'
      - '!release*'
jobs:
  basic_compile_and_test:
    name: "Conduct gradle managed test"
    runs-on: macos-latest
    steps:
      - name: "1: checking out repo"
        uses: actions/checkout@v4.2.2
      - name: "3: Config Java"
        uses: actions/setup-java@v4.6.0
        with:
          distribution: 'temurin'
          java-version: 17
      - name: "4: Config gradle"
        uses: gradle/gradle-build-action@v3.5.0
        with:
          gradle-version: 8.12.1
      - name: "5:Setup Android SDK"
        uses: android-actions/setup-android@v3
      - name: "6:Accept licenses"
        run: yes | sdkmanager --licenses || true
      - name: "7_1: testing "
        run: ./gradlew :testing:nexusOneApi30DebugAndroidTest --max-workers=1
      - name: "7_2: Compile apk"
        run: ./gradlew :app:assembleDebug